### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by Junkern** [oclif/parser#32]
I packed my cli with `oclif-dev pack:macos` and installed the pkg on my own computer. Upon executing this error appeared:

```
Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/stocli/node_modules/@oclif/parser/lib/index.js:4:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

My oclif dependencies are:

```
"@oclif/command": "^1.4.34",
"@oclif/config": "^1.6.33",
"@oclif/errors": "^1.1.2",
"@oclif/plugin-help": "^2.0.5",
```

I am on typescrit 2.9.2 and node 8.x

After manually adding `tslib` to my project dependencies I could start my CLI, but 
```
(node:19071) [MODULE_NOT_FOUND] Error Plugin: stocli: Cannot find module 'globby'
module: @oclif/config@1.6.33
```
appeared. That I fixed by installing globby.

**Comment by jdxcode** [comment]
fixed in https://github.com/oclif/parser/commit/05f89e04e21b95a4e262c9aebbe3809ada2db742
